export const titulosSeries = {
  es: {
    tendencia: "Series que son tendencia",
    populares: "Series populares",
    criticas: "Series con mejores criticas",
    aire: "Series al aire",
    busqueda: "Resultados para:",
  },
  in: {
    tendencia: "Trending series",
    populares: "Popular series",
    criticas: "Series with the best reviews",
    aire: "Series on the air",
  },
  ja: {
    tendencia: "トレンドシリーズ",
    populares: "人気シリーズ",
    criticas: "最高のレビューのシリーズ",
    aire: "放送中のシリーズ",
  },
  la: {
    tendencia: "Trending series",
    populares: "Popularis series",
    criticas: "Series cum optimis recensionibus",
    aire: "Series in aerem",
  },
  fr: {
    tendencia: "Série tendance",
    populares: "Série populaire",
    criticas: "Série avec les meilleures critiques",
    aire: "Série à l'antenne",
  },
  pt: {
    tendencia: "Série de tendências",
    populares: "Série popular",
    criticas: "Série com as melhores críticas",
    aire: "Série no ar",
  },
};

export const titulosPeliculas = {
  es: {
    tendencia: "Películas que son tendencia",
    populares: "Películas populares",
    criticas: "Películas  con mejores criticas",
    aire: "Películas  al aire",
    proximamente: "Películas a estrenarse",
  },
  in: {
    tendencia: "Movies that are trending",
    populares: "Popular movies",
    criticas: "Top rated movies",
    aire: "Movies on the air",
    proximamente: "New movies",
  },
  ja: {
    tendencia: "トレンドの映画",
    populares: "人気の映画",
    criticas: "最高評価の映画",
    aire: "放送中の映画",
    proximamente: "新しい映画",
  },
  la: {
    tendencia: "Movies quae sunt trending",
    populares: "Popularibus movies",
    criticas: "Top rated movies",
    aire: "Movies in aerem",
    proximamente: "Novum movies",
  },
  fr: {
    tendencia: "Films à la mode",
    populares: "Films populaires",
    criticas: "Films les mieux notés",
    aire: "Films à l'antenne",
    proximamente: "Nouveaux Filmss",
  },
  pt: {
    tendencia: "Filmes que estão em alta",
    populares: "filmes populares",
    criticas: "Filmes mais bem avaliados",
    aire: "filmes no ar",
    proximamente: "Novos filmes",
  },
};

export const titulosComunes = {
  es: {
    info: "Info",
    reparto: "Reparto",
    informacion: "Información",
    fecha: "Fecha de nacimiento: ",
    lugar: "Lugar de nacimiento: ",
    creditos: "Creditos",
    videos: "Videos",
    noDisponible: "Información no disponible.",
    episodios: "Episodios",
    temporada: "Temporada",
    similares: "Similares",
    duracion: "Duración:",
    genero: "Género: ",
    produccion: "Producción:",
    buscar: "Buscar",
    resultados: "Resultados para: ",
    footer: "Realizado por",
    error: "¡Ups! Ruta no encontrada",
    home: "Ir a Home",
    pagina: "Página",
  },
  in: {
    info: "Info",
    reparto: "Distribution",
    informacion: "Information",
    fecha: "Date of birth: ",
    lugar: "Place of birth: ",
    creditos: "Credits",
    videos: "Videos",
    noDisponible: "Information not available",
    episodios: "Episodes",
    temporada: "season",
    similares: "Similar",
    duracion: "Duration:",
    genero: "Gender: ",
    produccion: "Production:",
    buscar: "Search for",
    resultados: "Results for: ",
    footer: "Made by",
    error: "Oops! path not found",
    home: "Go to Home",
    pagina: "Page",
  },
  ja: {
    info: "情報",
    reparto: "分布",
    informacion: "情報",
    fecha: "生年月日： ",
    lugar: "出生地: ",
    creditos: "クレジット",
    videos: "ビデオ",
    noDisponible: "ビデオは利用できません",
    episodios: "エピソード",
    temporada: "季節",
    similares: "似ている",
    duracion: "間隔:",
    genero: "性別: ",
    produccion: "製造:",
    buscar: "検索する",
    resultados: "結果: ",
    footer: "作られた",
    error: "おっと！パスが見つかりません",
    home: "家に帰る",
    pagina: "ページ",
  },
  la: {
    info: "Info",
    reparto: "Distributio",
    informacion: "Informationes",
    fecha: "Diem natalis: ",
    lugar: "Locus nativitatis: ",
    creditos: "Credit",
    videos: "Videos",
    noDisponible: "Information not available",
    episodios: "Episodes",
    temporada: "Tempore",
    similares: "Similis",
    duracion: "Tempus:",
    genero: "Genus: ",
    produccion: "Fabricatio:",
    buscar: "Quarere",
    resultados: "Results for: ",
    footer: "Factum per",
    error: "Oops! iter non inveni",
    home: "Vade ad Home",
    pagina: "Pagina",
  },
  fr: {
    info: "Info",
    reparto: "Distribution",
    informacion: "Information",
    fecha: "Date de naissance: ",
    lugar: "Lieu de naissance: ",
    creditos: "Crédits",
    videos: "Vidéos",
    noDisponible: "Information non disponible",
    episodios: "Épisodes",
    temporada: "saison",
    similares: "Similaire",
    duracion: "durée:",
    genero: "Genres: ",
    produccion: "Production:",
    buscar: "Chercher",
    resultados: "Résultats pour: ",
    footer: "Réalisé par",
    error: "Oups! chemin introuvable",
    home: "Aller à la maison",
    pagina: "Page",
  },
  pt: {
    info: "informação",
    reparto: "Distribuição",
    informacion: "Em formação",
    fecha: "Data de nascimento: ",
    lugar: "Local de nascimento: ",
    creditos: "Créditos",
    videos: "Vídeos",
    noDisponible: "Informação não disponível",
    episodios: "Episódios",
    temporada: "Estação",
    similares: "Semelhante",
    duracion: "Duração:",
    genero: "Gênero: ",
    produccion: "Produção:",
    buscar: "Procurar",
    resultados: "Resultados para: ",
    footer: "Realizado por",
    error: "Ops! caminho não encontrado",
    home: "Ir para Home",
    pagina: "Página",
  },
};
export const urlBase = "https://api.themoviedb.org/3";

export const apiKey = "252843cc327f9e10875f92a24a03d130";
