export const titulosSeries = {
  es: {
    tendencia: "Series que son tendencia",
    populares: "Series populares",
    criticas: "Series con mejores criticas",
    aire: "Series al aire",
    busqueda: "Resultados para:",
  },
  in: {
    tendencia: "Trending series",
    populares: "Popular series",
    criticas: "Series with the best reviews",
    aire: "Series on the air",
  },
  ja: {
    tendencia: "トレンドシリーズ",
    populares: "人気シリーズ",
    criticas: "最高のレビューのシリーズ",
    aire: "放送中のシリーズ",
  },
  la: {
    tendencia: "Trending series",
    populares: "Popularis series",
    criticas: "Series cum optimis recensionibus",
    aire: "Series in aerem",
  },
  fr: {
    tendencia: "Série tendance",
    populares: "Série populaire",
    criticas: "Série avec les meilleures critiques",
    aire: "Série à l'antenne",
  },
  pt: {
    tendencia: "Série de tendências",
    populares: "Série popular",
    criticas: "Série com as melhores críticas",
    aire: "Série no ar",
  },
};

export const titulosPeliculas = {
  es: {
    tendencia: "Películas que son tendencia",
    populares: "Películas populares",
    criticas: "Películas  con mejores criticas",
    aire: "Películas  al aire",
    proximamente: "Películas a estrenarse",
  },
  in: {
    tendencia: "Movies that are trending",
    populares: "popular movies",
    criticas: "Top rated movies",
    aire: "Movies on the air",
    proximamente: "New movies",
  },
  ja: {
    tendencia: "トレンドの映画",
    populares: "人気の映画",
    criticas: "最高評価の映画",
    aire: "放送中の映画",
    proximamente: "新しい映画",
  },
  la: {
    tendencia: "Movies quae sunt trending",
    populares: "Popularibus movies",
    criticas: "Top rated movies",
    aire: "Movies in aerem",
    proximamente: "Novum movies",
  },
  fr: {
    tendencia: "Films à la mode",
    populares: "Films populaires",
    criticas: "Films les mieux notés",
    aire: "Films à l'antenne",
    proximamente: "Nouveaux Filmss",
  },
  pt: {
    tendencia: "Filmes que estão em alta",
    populares: "filmes populares",
    criticas: "Filmes mais bem avaliados",
    aire: "filmes no ar",
    proximamente: "Novos filmes",
  },
};

export const titulosComunes = {
  es: {
    info: "Info",
    reparto: "Reparto",
    informacion:"Información", 
    creditos:"Creditos",
    videos: "Videos",
    episodios: "Episodios",
    temporada: "Temporada",
    similares: "Similares",
    duracion: "Duración:",
    genero: "Género: ",
    produccion: "Producción:",
    buscar: "Buscar",
    resultados: "Resultados para: ",
    footer: "Realizado por",
  },
  in: {
    info: "Info",
    reparto: "Distribution",
    informacion:"Information", 
    creditos:"Credits",
    videos: "Videos",
    episodios: "Episodes",
    temporada: "season",
    similares: "Similar",
    duracion: "Duration:",
    genero: "Gender: ",
    produccion: "Production:",
    buscar: "Search for",
    resultados: "Results for: ",
    footer: "Made by",
  },
  ja: {
    info: "情報",
    reparto: "分布",
    informacion:"情報", 
    creditos:"クレジット",
    videos: "ビデオ",
    episodios: "エピソード",
    temporada: "季節",
    similares: "似ている",
    duracion: "間隔:",
    genero: "性別: ",
    produccion: "製造:",
    buscar: "検索する",
    resultados: "結果: ",
    footer: "作られた",
  },
  la: {
    info: "Info",
    reparto: "Distributio",
    informacion:"Informationes", 
    creditos:"Credit",
    videos: "Videos",
    episodios: "Episodes",
    temporada: "Tempore",
    similares: "Similis",
    duracion: "Tempus:",
    genero: "Genus: ",
    produccion: "Fabricatio:",
    buscar: "Quarere",
    resultados: "Results for: ",
    footer: "Factum per",
  },
  fr: {
    info: "Info",
    reparto: "Distribution",
    informacion:"Information", 
    creditos:"Crédits",
    videos: "Vidéos",
    episodios: "Épisodes",
    temporada: "saison",
    similares: "Similaire",
    duracion: "durée:",
    genero: "Genres: ",
    produccion: "Production:",
    buscar: "Chercher",
    resultados: "Résultats pour: ",
    footer: "Réalisé par",
  },
  pt: {
    info: "informação",
    reparto: "Distribuição",
    informacion:"Em formação", 
    creditos:"Créditos",
    videos: "Vídeos",
    episodios: "Episódios",
    temporada: "Estação",
    similares: "Semelhante",
    duracion: "Duração:",
    genero: "Gênero: ",
    produccion: "Produção:",
    buscar: "Procurar",
    resultados: "Resultados para: ",
    footer: "Realizado por",
  },
};
export const urlBase = "https://api.themoviedb.org/3";

export const apiKey = "252843cc327f9e10875f92a24a03d130";
